// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
// import About from '../components/About'
import Slider from '../components/Slider'
import Content from '../components/Content'

export default function Home() {
  return (
    <>
      
      <Head>
        <title>Gardeniary - Grow the Garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      <Slider></Slider>
      <Content></Content>
      <Footer></Footer>
    </>
  )
}
